DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(100) NOT NULL,
    requestor_id INTEGER NOT NULL REFERENCES users(id),
    created timestamp without time zone
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(100) NOT NULL,
    available boolean NOT NULL,
    owner_id INTEGER NOT NULL REFERENCES users(id),
    request_id INTEGER REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id INTEGER REFERENCES items(id),
    booker_id INTEGER REFERENCES users(id),
    status varchar(100)
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(100) NOT NULL,
    item_id INTEGER NOT NULL REFERENCES items(id),
    author_id INTEGER NOT NULL REFERENCES users(id),
    created timestamp without time zone
);